name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Flask app in background
        run: |
          nohup python app.py &
          sleep 5
      - name: Test app endpoint
        run: |
          curl -f http://localhost:5000 | grep 'Hello, World!'
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Simulate deployment
        run: |
          echo "Deploying application..."
          # Here you would add real deployment steps, e.g.,
          # scp, rsync, or use a cloud provider's CLI
          echo "Deployment complete." 